#!/usr/bin/env bash
set -e

version=1.0.0
d=/usr/local/bioinf-recipes/assembly-stats
mkdir $d
cd $d
wget https://github.com/sanger-pathogens/assembly-stats/archive/v$version.tar.gz
tar -zxf v$version.tar.gz
rm v$version.tar.gz
cd assembly-stats-$version
mkdir build
cd build
cmake ..
make
make test
make install
