#!/usr/bin/env bash
set -e

# install augustus
d=/usr/local/bioinf-recipes/augustus
mkdir $d
cd $d
version=3.2.1
wget http://bioinf.uni-greifswald.de/augustus/binaries/old/augustus-$version.tar.gz
tar -zxf augustus-$version.tar.gz
cd augustus-$version/
make
make install
chmod -R +rx /opt/augustus-$version/

# add 3D7 data

mkdir /usr/local/bioinf-recipes/augustus/augustus-$version/config/species/3D7
echo "AUGUSTUS_CONFIG_PATH=/usr/local/bioinf-recipes/augustus/augustus-$version/config" >> /etc/environment
# need to copy the 3d7 files from *somewhere* to /usr/local/bioinf-recipes/augustus/augustus-$version/config/species/3D7
