#!/usr/bin/env bash
set -e

# install augustus
d=/usr/local/bioinf-recipes/augustus
mkdir $d
cd $d
wget http://bioinf.uni-greifswald.de/augustus/binaries/augustus.current.tar.gz
tar -zxf augustus.current.tar.gz
version=$(ls | awk -F"-" '!/current/ {print $2}')
cd augustus-$version/
make
make install
chmod -R +rx /opt/augustus-3.2.1/

# add 3D7 data
/usr/local/bioinf-recipes/augustus/augustus-3.2.1/config/


mkdir /usr/local/bioinf-recipes/augustus/augustus-$version/config/species/3D7
echo "AUGUSTUS_CONFIG_PATH=/usr/local/bioinf-recipes/augustus/augustus-$version/config" >> /etc/environment
# need to copy the 3d7 files from *somewhere* to /usr/local/bioinf-recipes/augustus/augustus-$version/config/species/3D7
