#!/usr/bin/env bash
set -e

version=0.15.0
cd /tmp
wget https://github.com/sanger-pathogens/circlator/archive/v$version.tar.gz
tar -zxf v$version.tar.gz
rm v$version.tar.gz
cd circlator-$version/
python3 setup.py test
python3 setup.py install
cd ..
rm -fr circlator-$version/
