#!/usr/bin/env bash
set -e

cd /usr/local/bioinf-recipes/
git clone https://github.com/sanger-pathogens/gubbins.git
cd gubbins
autoreconf -i
./configure
make
make check
make install
# fix to find gubbins library. Stops this error:
# error while loading shared libraries: libgubbins.so.0
rm /usr/local/bin/gubbins
ln -s /usr/local/bioinf-recipes/gubbins/src/gubbins /usr/local/bin/gubbins
