#!/usr/bin/env bash
set -e

cd /tmp
wget  http://pypi.python.org/packages/source/D/DendroPy/DendroPy-3.12.0.tar.gz
tar xzvf DendroPy-3.12.0.tar.gz
cd DendroPy-3.12.0
sudo python setup.py install
cd ..
rm -fr DendroPy-3.12.0*
sudo add-apt-repository --yes ppa:ap13/gubbins
sudo apt-get update
sudo apt-get install --force-yes -y fasttree raxml fastml2 gubbins

