#!/usr/bin/env bash
set -e

version=0.43.0
cd /usr/local/bioinf-recipes/
git clone --recursive https://github.com/pachterlab/kallisto.git
cd kallisto
git checkout v$version
git submodule update --recursive

mkdir build
cd build
cmake ..
make
make install
