#!/usr/bin/env bash
set -e

d=/usr/local/bioinf-recipes/pbcr
mkdir $d
cd $d
wget http://sourceforge.net/projects/wgs-assembler/files/wgs-assembler/wgs-8.3/wgs-8.3rc2-Linux_amd64.tar.bz2
tar -xjf wgs-8.3rc2-Linux_amd64.tar.bz2
cd wgs-8.3rc2/Linux-amd64/bin

for x in `ls -p | grep -v /`
do
    ln -s $PWD/$x /usr/local/bin/$x
done
