#!/usr/bin/env bash
set -e

version=3.2.2
d=/usr/local/bioinf-recipes/
cd $d
wget https://cran.r-project.org/src/base/R-3/R-$version.tar.gz 
tar -xvf R-$version.tar.gz
pushd R-$version && ./configure --with-readline=no --with-x --with-cairo && make && sudo make install && popd

#Install modules
Rscript -e "install.packages(c('httpuv', 'caTools', 'mime', 'jsonlite', 'htmltools', 'R6', 'sourcetools', 'xtable', 'ggplot2', 'dplyr', 'data.table', 'tidyr', 'reshape2', 'lazyeval', 'RcppArmadillo', 'Hmisc', 'XML', 'matrixStats', 'pheatmap', 'aggregation'), repos='http://www.stats.bris.ac.uk/R/')"
Rscript -e "source('http://bioconductor.org/biocLite.R')" -e "biocLite(c('rhdf5', 'S4Vectors', 'IRanges', 'GenomicRanges', 'Biobase', 'BiocParallel', 'genefilter', 'geneplotter'))"
