#!/usr/bin/env bash
set -e

version=1.2
cd /usr/local/bioinf-recipes/
wget https://github.com/samtools/samtools/releases/download/$version/samtools-$version.tar.bz2
tar -xjf samtools-$version.tar.bz2
rm samtools-$version.tar.bz2
cd samtools-$version
make
ln -s /usr/local/bioinf-recipes/samtools-$version/samtools /usr/local/bin/samtools-$version
ln -s /usr/local/bioinf-recipes/samtools-$version/samtools /usr/local/bin/samtools-1
